apiVersion: v1
kind: Pod
metadata:
  name: lb
  labels:
    course: devops
    trainer: siva
spec:
  containers:
  - name: folb
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxlb
spec:
  type: LoadBalancer
  selector:
    course: devops
    trainer: siva
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80 


     