apiVersion: v1
kind: Pod
metadata:
  name: cnodeport
  labels:
    usedfor: nodeport
    app: ndport
spec:
  containers:
  - name: fornodeport
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    usedfor: nodeport
    app: ndport
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000  # You can specify the NodePort here (30000 is just an example)


     