apiVersion: v1
kind: Pod
metadata:
  name: container
  labels:
    type: container
    purpose: web
  annotations:
    example: "sample %#$%^"
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80  

---
apiVersion: v1
kind: Service
metadata:
  name: nginxservice
  labels:
    type: container
spec:
  selector:
    type: container
    purpose: web
  ports:
    - protocol: "TCP"  # Corrected from "tcp" to "TCP"
      port: 80
      targetPort: 80
