apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    COURSE: DevOps
    Trainer: "me ef"
    annotations:
      com.roboshop.trainer: "1212hrs"
      jenkins.url: "https://jenkins.com/roboshop"
spec:
  containers:
  - name: annota
    image: nginx
    ports:
    - containerPort: 80
  
  